FROM nginx:latest

# Copier le code front-end
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end

# Copier la configuration Nginx
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf

